Problem Name: Shape and Reshape

Link: https://www.hackerrank.com/challenges/np-shape-reshape/problem

Solution:

In [3]:
import numpy

arr = list(map(int, input().split()))
arr = numpy.array(arr)
arr = arr.reshape(3,3)
print(arr)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
